server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  neo4j:
      url: neo4j://localhost:7687 #4.x
      username: neo4j
      password: hxy230407198
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/kg?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: hxy230407198
      type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
file:
  serverurl:  http://localhost:8080
  location : /www/wwwroot/kgManger #D:\\kgmanager\\csv\\   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/"

agent:
  relationPatterns: classpath:agent/relation-patterns.txt
  predicateSynonyms: classpath:agent/predicate-synonyms.txt
  minRelationConfidence: 0.55
  maxCharDistance: 40
